### PR TITLE
Destructure resData for better readability

### PR DESCRIPTION
**Pull request by LahcenHaouch**

### CODE REVIEW

**Comment by TheYuriG** [comment]
@LahcenHaouch thanks for the PR!

I really liked how you concisely defined properties within setState. I didn't think about doing that and otherwise wouldn't have.

I don't know if you checked for issue #2 previously or if this PR also nearly accomplished its goal by accident, but `resData.errors` is still checked twice. The way I described in that issue was to nest IF statements to only check for `resData.errors` once, where if it failed the `statusCode` check, it would automatically throw the second error case without another check.

Example:
```
//? Check if we got any errors
if (errors) {
	//? Check specifically if the server returned an
	//? Unauthorized status code and throw that error
	if (errors?.[0]?.status === 401) {
		throw new Error('Failed to fetch post, you are not authenticated!');
	}
	//? If it's not an Unauthorized status code, then throw the default error message
	throw new Error('Unable to retrieve post!');
}
```

The second detail is that you are destructuring data twice, rather than just once as requested in the issue. GraphQL sometimes can be hard to work with, so destructuring all of the properties in a single place helps any newcomers to understand how the data is returned to us by the backend server.

Example:
Instead of
```
...
.then(({errors, data}) => {
...
const { singlePost: { title, creator: { name: author }, imageUrl, createdAt: date, content}} = data
...
```
it would be preferable to have
````
...
.then({errors, data: {
	singlePost: {
		title,
		imageUrl,
		createdAt,
		content,
		creator: { name },
		},
	},
}) => {
...
```

Feel free to make these new changes if you feel like it, else I'm gonna get to them after I finish updating the other of the REST endpoints to GraphQL this week or the next.

**Comment by LahcenHaouch** [comment]
Hey @TheYuriG ,

Thanks for the feedback, I will push the requested changes right away

**Review by TheYuriG — APPROVED** [review]
Looks good to me, the code was updated as requested. The comments are outdated or misplaced, but I'll fix that in my next commit once I get to work on the files again. Good job and thank you for the PR!

**Comment by TheYuriG** [comment]
The comments were far less problematic upon closer inspection than I thought. moved the `Check specifically [...]` comments two lines down and added `//? Check if we got any errors` in its place and we were good to go.

**Comment by LahcenHaouch** [comment]
Cheers,
I'll keep an eye out for future issues

**Pull request merged**
